baseURL = "https://reezaras.com/"
languageCode = "en-us"
title = "Reza Rasouli"

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  coverImage = "plants.jpg"
  favicon = "/favicon.png"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'

[author]
twitter = "reezaras"
name = "Reza Rasouli"
job = "Software Developer, Distributed System Passionate"
picture = "images/profile/pic.jpg"


[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"

[[menu.main]]
  weight = 2
  identifier = "blog"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/"

[[menu.main]]
  weight = 3
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-code\"></i>"
  url = "/"

[[menu.main]]
  weight = 4
  identifier = "aboutme"
  name = "About me"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-child\"></i>"
  url = "/"


